services:
  web:
    build: .
    platform: linux/amd64
    container_name: dujiaoka
    ports:
      - "80:80"
      - "9000:9000"
    volumes:
      # 映射整个项目代码，使得修改代码能够即时生效
      - .:/app
      # 增加此行，确保将上传的资源映射出来，避免容器重新创建后图片不在了
      - ./data/public/uploads:/app/public/uploads
    environment:
      WEB_DOCUMENT_ROOT: "/app/public"
      TZ: Asia/Shanghai
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: dujiaoka
      DB_USERNAME: dujiaoka
      DB_PASSWORD: dujiaoka123
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mysql
      - redis
    tty: true
    restart: always

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: dujiaoka_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: dujiaoka
      MYSQL_USER: dujiaoka
      MYSQL_PASSWORD: dujiaoka123
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "13306:3306"
      
  redis:
    image: redis:6
    platform: linux/amd64
    container_name: dujiaoka_redis
    restart: always
    ports:
      - "16379:6379"
